version: 1.0.0
title: Nostr Client Development
description: A recipe for building Nostr client applications
instructions: Create a Nostr client application according to the user's request.
extensions:
  - type: builtin
    name: developer
    display_name: Developer Tools
    timeout: 300
    bundled: true
  - type: stdio
    name: nostr
    cmd: npx
    args:
      - -y
      - xjsr
      - "@nostrbook/mcp"
    envs: {}
    timeout: 20
    description: null
    bundled: null
  - type: stdio
    name: fetch
    cmd: uvx
    args:
      - mcp-server-fetch
    envs: {}
    timeout: 20
    description: null
    bundled: null
author:
  contact: Alex Gleason <alex@alexgleason.me>
